name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build packages
      run: yarn run build

    - name: Publish packages
      run: npx lerna publish from-package --no-verify-access --force-publish --yes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
