name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build packages
      run: yarn run build

    - name: Publish packages
      run: yarn lerna publish --yes
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
